sudo: required
dist: precise
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - node -v
  - yarn
script:
  - yarn lint
  - yarn prettier:ci
  - yarn test
  - yarn flow
